# Generated by Django 5.0.6 on 2024-06-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sum', models.PositiveIntegerField(verbose_name='Cумма платежа')),
                ('payment_method', models.CharField(choices=[('наличными', 'наличными'), ('переводом', 'переводом')], max_length=50, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
